### ISSUE TITLE
Can you share your waybar config?

### ISSUE THREAD

**Issue by giannilabella** [ericmurphyxyz/archrice#11]
Really liked the bar you had in the last videos (the videos too), but it isn't in the repo. Do you mind sharing it?

Btw, do you use the wayland fork of rofi or the original one? Because I was having some problems building the wayland fork from source and the original is in the official packages. Do you know if there are any practical differences?

**Comment by dankuri** [comment]
@giannilabella if it's still relevant to you, check out the `hyprland` branch, this is where the new configs are stored.

**Comment by giannilabella** [comment]
oh, didn't see that, thanks
