### ISSUE TITLE
Change directory for config files

### ISSUE THREAD

**Issue by LinuxedZ** [ericmurphyxyz/archrice#15]
you have your username in your config files, however what you should do is do ~/ instead of /home/username/ as to make it so people dont have to manually change it

**Comment by ericmurphyxyz** [comment]
Good point. I changed all `/home/eric/` to `~/` in 14f6177686787e9288ccbbb99274d0e06c9cc8f0, except for `dunstrc`, which doesn't work without the explicit path for whatever reason. If anyone knows how to fix that, I'll accept a pull request for that.

**Comment by nirmitjoshi** [comment]
What we can do is use `envsubst` to open dunst and it will replace the environment variables in dunstrc automatically.

**Comment by nirmitjoshi** [comment]
> What we can do is use `envsubst` to open dunst and it will replace the environment variables in dunstrc automatically.

here's PR for the same - #18
