### ISSUE TITLE
Organizing zsh plugins in the dotfiles repository?

### ISSUE THREAD

**Issue by 766F6964** [ericmurphyxyz/archrice#20]
I noticed that in your dotfiles repository, specifically within the `.config/zsh` directory, only the `.zshrc` and `.p10k.zsh` files are provided. The `.zshrc` file depends on several plugins, such as _zsh-syntax-highlighting_, _zsh-history-substring-search_, _you-should-use_, and _zsh-auto-suggestions_. I'm curious as to why these plugins are not included. Do you install them externally?

I am asking this primarily to organize my own dotfiles better, and I am curious about your approach.
For instance, the _you-should-use_ plugin is a simple .zsh file that could easily be included in the repository. However, other plugins, like _zsh-auto-suggestions_, consist of multiple interconnected .zsh files.

What do you think is the best approach to organize these plugins more efficiently?

- Exclude all plugins and manually install each one. This approach would complicate setting up a new system with the dotfiles due to the additional manual steps.
- Include only the single-file plugins, excluding the others. This still introduces some manual overhead.
- Include all plugins, which can be challenging as it requires determining which files are essential. Some have many files, that wouldn't not need to be in the dotfiles repository.
- Use submodules for some of the plugins.

**Comment by ericmurphyxyz** [comment]
My zsh plugins have been pretty unorganized for a while. I was just manually installing them every time I set up a new computer, which was not the most efficient way to do it. After seeing this, I ended up reorganizing my [`.zshrc`](https://github.com/ericmurphyxyz/dotfiles/blob/master/.config/zsh/.zshrc) and adding a simple script so all the plugins will automatically be installed the first time you run zsh. Hope that helps you organize your own dotfiles in some way.
