### ISSUE TITLE
lf kitty files what am i doing wrong ?

### ISSUE THREAD

**Issue by thorrrr** [ericmurphyxyz/archrice#6]
HI Eric
I have copied your lf files for kitty to my lf folder and changed the directory from eric to my name in the lf_kitty_previews temp directory line 12.
But when i run kitty and us lf to view images nothing happens?

**Comment by ericmurphyxyz** [comment]
Did you make lf_kitty_preview and lf_kitty_clean executable? (e.g. `chmod +x lf_kitty_preview lf_kitty_clean`)

**Comment by thorrrr** [comment]
HI Eric
When i dropped them in they show as text files 
https://i.imgur.com/dbrBMNo.png

I have now fixed the images by removing the .txt from all the files 

On a secondary question how do i get engage nvim to open up a doc if i need to edit it from lf ?

**Comment by ericmurphyxyz** [comment]
Sorry I didn't see this earlier, but I set my `$EDITOR` variable as `nvim` and use the default `e` keybinding.
